Section "InputClass"
    Identifier "Mouse"
    MatchIsPointer "on"
    MatchProduct "Logitech USB Optical Mouse"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "-0.4"
EndSection

Section "InputClass"
    Identifier "Touchpad"
    MatchIsTouchpad "on"
    MatchProduct "SynPS/2 Synaptics TouchPad"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "-0.2"
    Option "DisableWhileTyping" "true"
    Option "ScrollMethod" "twofinger"
EndSection
